---
title: "Label values along ecdf curve"
author: "Harris"
date: 2017-12-22T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r, echo= FALSE}
suppressPackageStartupMessages(library(tidyverse))
```

# fake data

```{r}
test_df <- data.frame(values = c(rnorm(1000), rep(-2, 50), rnorm(50)),
                      letter = c(rep("a",1000),rep("b",100)))
```

# Need to find the value of the cumulative probability at a certain time value.
Enter: `ecdf()`

## One at a time:
```{r}
(p_0_a <- ecdf(filter(test_df, letter == "a")$values)(0))
(p_0_b <- ecdf(filter(test_df, letter == "b")$values)(0))
```

## Or all at once:

### Step 1: `nest` the data inside a new column.
```{r}
test_df %>% 
  group_by(letter) %>% 
  nest(values)
```

### Step 2: Shove that data into the `ecdf` function; and go ahead and evaluate at datapoint 0; drop the nested data

```{r}
labels <- test_df %>% 
  group_by(letter) %>% 
  nest(values) %>% 
  mutate(y_at_0 = map_dbl(data, ~ecdf(.x$values)(0))) %>% 
  select(-data) %>% 
  print()
```

### Step 3: plot it.

```{r}
ggplot(data = test_df, aes(x = values, col = letter)) +
  stat_ecdf(pad = FALSE) +
  coord_cartesian(xlim = c(-3,0)) + 
  geom_text(data = labels, aes(x=0, y=y_at_0, label = paste(letter, scales::percent(y_at_0))), vjust = -0.25, hjust = 1)
```

# This works because `ecdf` returns a function that takes in a value to evaluate

```{r}
# returns a function
str(ecdf(test_df$values))
```